// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: logic.proto

package proto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Logic service

type LogicService interface {
	Single(ctx context.Context, in *SingleReq, opts ...client.CallOption) (*SingleReply, error)
}

type logicService struct {
	c    client.Client
	name string
}

func NewLogicService(name string, c client.Client) LogicService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &logicService{
		c:    c,
		name: name,
	}
}

func (c *logicService) Single(ctx context.Context, in *SingleReq, opts ...client.CallOption) (*SingleReply, error) {
	req := c.c.NewRequest(c.name, "Logic.single", in)
	out := new(SingleReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Logic service

type LogicHandler interface {
	Single(context.Context, *SingleReq, *SingleReply) error
}

func RegisterLogicHandler(s server.Server, hdlr LogicHandler, opts ...server.HandlerOption) error {
	type logic interface {
		Single(ctx context.Context, in *SingleReq, out *SingleReply) error
	}
	type Logic struct {
		logic
	}
	h := &logicHandler{hdlr}
	return s.Handle(s.NewHandler(&Logic{h}, opts...))
}

type logicHandler struct {
	LogicHandler
}

func (h *logicHandler) Single(ctx context.Context, in *SingleReq, out *SingleReply) error {
	return h.LogicHandler.Single(ctx, in, out)
}
